### ISSUE TITLE
Disable WiFi power management to improve WiFi performance

### ISSUE THREAD

**Issue by maximkulkin** [hbrc-fpga-class/class-material#1]
Raspberry Pi 3 has some nasty problem with WiFi chip which results in very slow WiFi connection. It is recommended to disable WiFi power management to make WiFi more stable. Do disable WiFi power management you need to run this command:
```shell
sudo iwconfig wlan0 power off
```
You can conveniently put it into /etc/rc.local:
```shell
#!/bin/bash

iwconfig wlan0 power off
```

Corresponding thread on RPi forum: 
https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=138312#p917983

**Comment by swedishhat** [comment]
This is a good suggestion -- thanks for that. I'd be interested in seeing how it affects overall power consumption of the bot and if that causes any noticeable changes to battery life

**Comment by maximkulkin** [comment]
Haven't done any testing but common sense hints that it's not the best mode to run on battery in the fields, but for development (when running from wall power supply) it's a must.
